# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2500767c3d5c67da384532ea565224dff33322250fba1a89d7e5418ee787381f3982016f0acd36865640db589278caa3f5f4a7169578aff1373194b4f17e810e

test:
  secret_key_base: 74077cab634ee5354ef03f29a907529c9e344b17b6d811edcd4d90bd6316ce9f6bdcf5039ed6e9dba930cdbd173da29c2615609e64cfbbede0e72fde21cc5183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
